define([], function () {
  return {
    PropertyPaneDescription: "Description",
    BasicGroupName: "Group Name",
    DescriptionFieldLabel: "Description Field",
    AddAssessments: "Add Assessments",
    CreateProjectRequest: "Create Project Request",
    ProjectInformation: "Project Information",
    ProjectID: "Project ID",
    FormNumber: "Form Number",
    Title: "Title",
    CustomerName: "Customer Name",
    ProjectCodeLabel: "Project Code",
    RequestDate: "Request Date",
    RequestNote: "Request Note",
    RequestTitle: "Request Title",
    Customer: "Customer",
    SelectCustomer: "Select Customer",
    EstimatedDuration: "Estimated Duration (days)",
    EstimatedCost: "Estimated Cost",
    Create: "Create",
    Cancel: "Cancel",
    TechnicalAssessments: "Technical Assessments",
    Activity: "Activity",
    HumanResource: "HumanResource",
    Machine: "Machine",
    Material: "Material",
    AddAssessment: "Add Assessment",
    FinalSubmit: "Final Submit",
    Quantity: "Quantity",
    PricePerUnit: "Price Per Unit",
    TotalCost: "Total Cost",
    Remove: "Remove",
    No: "No",
    AddedYet: "Added yet",
    Add: "Add",
    FormModeFieldLabel: "Form Mode",
    FormModeCreate: "Create",
    FormModeEdit: "Edit",
    FormModeView: "View",
    ItemIdFieldLabel: "Item ID",
    ItemIdFieldDescription: "Required for Edit and View modes",
    EditProjectRequest: "Edit Project Request",
    ViewProjectRequest: "View Project Request",
    Update: "Update",
    Back: "Back",
    ProjectRequestUpdatedSuccessfully: "Project request updated successfully",
    ErrorUpdatingProjectRequest: "Error updating project request",
    ErrorLoadingProjectRequest: "Error loading project request",
    Loading: "Loading...",
    CurrentViewFieldLabel: "Current View",
    ListView: "List View",
    FormView: "Form View",

    // Additional keys referenced in your components:
    Select: "Select",
    Action: "Action",
    Status: "Status",
    Actions: "Actions",
    View: "View",
    Edit: "Edit",
    AllStatuses: "All Statuses",
    StatusNew: "New",
    StatusInReview: "In Review",
    StatusApproved: "Approved",
    StatusRejected: "Rejected",
    FilterByStatus: "Filter by Status",
    SelectStatus: "Select a Status",
    CreateNewRequest: "Create New Request",
    LoadingProjects: "Loading Projects...",
    ProjectRequests: "Project Requests",
    RequestTitleRequired: "Request Title is required",
    CustomerRequired: "Customer is required",
    ProjectRequestCreatedSuccessfully: "Project request created successfully",
    ErrorCreatingProjectRequest: "Error creating project request",
    BackToList: "Back to List",
    Step: "Step",
    Of: "of",
  };
});
