define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    
    AddAssessments: "افزودن ارزیابی‌ها",
    CreateProjectRequest: "ایجاد درخواست پروژه",
    ProjectInformation: "اطلاعات پروژه",
    ProjectID: "شناسه پروژه",
    FormNumber: "شماره فرم",
    Title: "عنوان",
    CustomerName: "نام مشتری",
    RequestDate: "تاریخ درخواست",
    RequestNote: "یادداشت درخواست",
    RequestTitle: "عنوان درخواست",
    Customer: "مشتری",
    SelectCustomer: "انتخاب مشتری",
    EstimatedDuration: "مدت زمان تخمینی (روزها)",
    EstimatedCost: "هزینه تخمینی",
    Create: "ایجاد",
    Cancel: "لغو",
    TechnicalAssessments: "ارزیابی‌های فنی",
    Activity: "فعالیت",
    HumanResource: "نیروی انسانی",
    Machine: "ماشین آلات",
    Material: "مواد",
    AddAssessment: "افزودن ارزیابی",
    FinalSubmit: "ارسال نهایی",
    Quantity: "مقدار",
    PricePerUnit: "قیمت هر واحد",
    TotalCost: "هزینه کل",
    Remove: "حذف",
    No: "بدون",
    AddedYet: "هنوز اضافه نشده است",
    Add:"افزودن"
  }
});