declare interface IPrmWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  AddAssessments: string;
  CreateProjectRequest: string;
  ProjectInformation: string;
  ProjectID: string;
  FormNumber: string;
  Title: string;
  CustomerName: string;
  ProjectCodeLabel: string;
  RequestDate: string;
  RequestNote: string;
  RequestTitle: string;
  Customer: string;
  SelectCustomer: string;
  EstimatedDuration: string;
  EstimatedCost: string;
  Create: string;
  Cancel: string;
  TechnicalAssessments: string;
  Activity: string;
  HumanResource: string;
  Machine: string;
  Material: string;
  AddAssessment: string;
  FinalSubmit: string;
  Quantity: string;
  PricePerUnit: string;
  TotalCost: string;
  Remove: string;
  No: string;
  AddedYet: string;
  Add: string;
  FormModeFieldLabel: string;
  FormModeCreate: string;
  FormModeEdit: string;
  FormModeView: string;
  ItemIdFieldLabel: string;
  ItemIdFieldDescription: string;
  EditProjectRequest: string;
  ViewProjectRequest: string;
  Update: string;
  Back: string;
  ProjectRequestUpdatedSuccessfully: string;
  ErrorUpdatingProjectRequest: string;
  ErrorLoadingProjectRequest: string;
  Loading: string;
  CurrentViewFieldLabel: string;
  ListView: string;
  FormView: string;

  // Additional keys
  Action: string;
  Status: string;
  Actions: string;
  View: string;
  Edit: string;
  AllStatuses: string;
  StatusNew: string;
  StatusInReview: string;
  StatusApproved: string;
  StatusRejected: string;
  FilterByStatus: string;
  SelectStatus: string;
  CreateNewRequest: string;
  LoadingProjects: string;
  ProjectRequests: string;
  RequestTitleRequired: string;
  CustomerRequired: string;
  ProjectRequestCreatedSuccessfully: string;
  ErrorCreatingProjectRequest: string;
  BackToList: string;
  Step: string;
  Of: string;
}

declare module 'PrmWebPartStrings' {
  const strings: IPrmWebPartStrings;
  export = strings;
}
